<#
.SYNOPSIS
  Build arm64 Docker image, export it, and create an offline deployment bundle on a target drive.
.PARAMETER TargetDrive
  Drive letter for the SD card or USB stick (default: F).
.PARAMETER ImageName
  Docker image name (default: tricorder-neural).
.PARAMETER ImageTag
  Docker image tag (default: latest).
.PARAMETER Platform
  Docker buildx platform (default: linux/arm64).
.PARAMETER SkipBuild
  Skip the Docker build step (reuse existing image).
#>
[CmdletBinding()]
param(
    [string]$TargetDrive = "F",
    [string]$ImageName = "tricorder-neural",
    [string]$ImageTag = "latest",
    [string]$Platform = "linux/arm64",
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$FullImageRef = "${ImageName}:${ImageTag}"
$BundleDir = Join-Path "${TargetDrive}:" "tricorder-deploy"

Write-Host "`n=== Tricorder Offline Bundle Builder ===" -ForegroundColor Cyan
Write-Host "  Image:      $FullImageRef"
Write-Host "  Platform:   $Platform"
Write-Host "  Bundle dir: $BundleDir`n"

# Step 1: Build arm64 image with buildx
if (-not $SkipBuild) {
    Write-Host "[1/6] Building Docker image for $Platform ..." -ForegroundColor Yellow
    docker buildx build `
        --platform $Platform `
        --tag $FullImageRef `
        --load `
        -f "$ProjectRoot\Dockerfile" `
        $ProjectRoot
    if ($LASTEXITCODE -ne 0) { throw "Docker build failed" }
    Write-Host "[OK]  Image built: $FullImageRef`n" -ForegroundColor Green
} else {
    Write-Host "[1/6] Skipping build (--SkipBuild)`n" -ForegroundColor DarkGray
}

# Step 2: Verify image exists
Write-Host "[2/6] Verifying image ..." -ForegroundColor Yellow
docker image inspect $FullImageRef 2>$null | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Image '$FullImageRef' not found locally. Run without -SkipBuild." }
Write-Host "[OK]  Image verified`n" -ForegroundColor Green

# Step 3: Create bundle directory on target drive
Write-Host "[3/6] Preparing bundle directory: $BundleDir ..." -ForegroundColor Yellow
if (-not (Test-Path "${TargetDrive}:")) {
    throw "Drive ${TargetDrive}: is not accessible. Insert SD card / USB stick and retry."
}
New-Item -ItemType Directory -Force -Path $BundleDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BundleDir "config") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BundleDir "scripts") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BundleDir "scripts\lib") | Out-Null
Write-Host "[OK]  Directories created`n" -ForegroundColor Green

# Step 4: Export image as tar
$TarFile = Join-Path $BundleDir "$ImageName-$ImageTag.tar"
Write-Host "[4/6] Exporting image to $TarFile ..." -ForegroundColor Yellow
Write-Host "       This may take a few minutes for arm64 images."
docker save -o $TarFile $FullImageRef
if ($LASTEXITCODE -ne 0) { throw "docker save failed" }
$tarSize = (Get-Item $TarFile).Length / 1MB
Write-Host "[OK]  Image exported ($([math]::Round($tarSize,1)) MB)`n" -ForegroundColor Green

# Step 5: Copy deployment artifacts
Write-Host "[5/6] Copying deployment artifacts ..." -ForegroundColor Yellow
$artifacts = @(
    @{ Src = "docker-compose.yml";           Dest = "docker-compose.yml" }
    @{ Src = "config\base.yaml";             Dest = "config\base.yaml" }
    @{ Src = "config\production.yaml";       Dest = "config\production.yaml" }
    @{ Src = "scripts\deploy.defaults.sh";   Dest = "scripts\deploy.defaults.sh" }
    @{ Src = "scripts\pi-install.sh";        Dest = "scripts\pi-install.sh" }
    @{ Src = "scripts\pi-configure.sh";      Dest = "scripts\pi-configure.sh" }
    @{ Src = "scripts\pi-deploy.sh";         Dest = "scripts\pi-deploy.sh" }
    @{ Src = "scripts\rsync-excludes.txt";   Dest = "scripts\rsync-excludes.txt" }
    @{ Src = "scripts\lib\health-check.sh";  Dest = "scripts\lib\health-check.sh" }
    @{ Src = "scripts\pi-load-image.sh";     Dest = "scripts\pi-load-image.sh" }
)
foreach ($a in $artifacts) {
    $srcPath = Join-Path $ProjectRoot $a.Src
    $dstPath = Join-Path $BundleDir $a.Dest
    if (Test-Path $srcPath) {
        Copy-Item -Path $srcPath -Destination $dstPath -Force
        Write-Host "  Copied $($a.Src)" -ForegroundColor DarkGray
    } else {
        Write-Warning "  Missing: $srcPath (skipped)"
    }
}

# Write .env
$envContent = @"
# Generated by bundle-to-drive.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
TRICORDER_IMAGE=${FullImageRef}
TRICORDER_PORT=8000
TRICORDER__ENVIRONMENT=production
"@
Set-Content -Path (Join-Path $BundleDir ".env") -Value $envContent
Write-Host "  Wrote .env" -ForegroundColor DarkGray
Write-Host "[OK]  Artifacts copied`n" -ForegroundColor Green

# Step 6: Generate checksums
Write-Host "[6/6] Generating checksums ..." -ForegroundColor Yellow
$checksumFile = Join-Path $BundleDir "SHA256SUMS.txt"
$filesToHash = Get-ChildItem -Path $BundleDir -Recurse -File | Where-Object { $_.Name -ne "SHA256SUMS.txt" }
$lines = foreach ($f in $filesToHash) {
    $hash = (Get-FileHash -Algorithm SHA256 -Path $f.FullName).Hash.ToLower()
    $rel = $f.FullName.Substring($BundleDir.Length + 1).Replace("\", "/")
    "$hash  $rel"
}
Set-Content -Path $checksumFile -Value ($lines -join "`n")
Write-Host "[OK]  Checksums written to SHA256SUMS.txt`n" -ForegroundColor Green

# Summary
Write-Host "=== Bundle Complete ===" -ForegroundColor Cyan
Write-Host "  Location:   $BundleDir"
Write-Host "  Image tar:  $ImageName-$ImageTag.tar ($([math]::Round($tarSize,1)) MB)"
Write-Host "  Artifacts:  $($artifacts.Count) files + .env + checksums"
Write-Host ""
Write-Host "To deploy on Pi:" -ForegroundColor Yellow
Write-Host "  1. Insert SD/USB into Pi"
Write-Host "  2. Mount the drive:  sudo mount /dev/sda1 /mnt/usb"
Write-Host "  3. Run:  sudo bash /mnt/usb/tricorder-deploy/scripts/pi-load-image.sh /mnt/usb/tricorder-deploy"
Write-Host ""
