#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# bundle-to-drive.sh — Build arm64 Docker image, export it, and create an
# offline deployment bundle on a target directory (SD card, USB stick, etc.)
#
# Cross-platform replacement for bundle-to-drive.ps1 (works on macOS & Linux).
#
# Usage:
#   bash scripts/bundle-to-drive.sh /Volumes/SDCARD/tricorder-deploy
#   bash scripts/bundle-to-drive.sh /mnt/usb/tricorder-deploy
#   SKIP_BUILD=1 bash scripts/bundle-to-drive.sh /tmp/test-bundle
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"

# shellcheck source=scripts/lib/colors.sh
source "${SCRIPT_DIR}/lib/colors.sh"
# shellcheck source=scripts/deploy.defaults.sh
source "${SCRIPT_DIR}/deploy.defaults.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
TARGET_DIR="${1:-}"
IMAGE_NAME="${TRICORDER_IMAGE_NAME}"
IMAGE_TAG="${TRICORDER_IMAGE_TAG}"
PLATFORM="${TRICORDER_PLATFORM%%,*}"  # Use first platform for single-arch build
FULL_IMAGE_REF="${IMAGE_NAME}:${IMAGE_TAG}"
SKIP_BUILD="${SKIP_BUILD:-0}"

if [[ -z "${TARGET_DIR}" ]]; then
    echo "Usage: $(basename "$0") <target-directory>"
    echo ""
    echo "  <target-directory>  Path to the bundle output directory."
    echo "                      e.g. /Volumes/SDCARD/tricorder-deploy"
    echo ""
    echo "Environment variables:"
    echo "  SKIP_BUILD=1        Skip the Docker build step (reuse existing image)"
    echo "  TRICORDER_IMAGE_NAME  Docker image name (default: ${IMAGE_NAME})"
    echo "  TRICORDER_IMAGE_TAG   Docker image tag (default: ${IMAGE_TAG})"
    exit 1
fi

section "Tricorder Offline Bundle Builder"
info "Image:      ${FULL_IMAGE_REF}"
info "Platform:   ${PLATFORM}"
info "Bundle dir: ${TARGET_DIR}"

# ---------------------------------------------------------------------------
# Step 1: Build arm64 image with buildx
# ---------------------------------------------------------------------------
if [[ "${SKIP_BUILD}" == "1" ]]; then
    info "[1/6] Skipping build (SKIP_BUILD=1)"
else
    section "[1/6] Building Docker image for ${PLATFORM}"
    docker buildx build \
        --platform "${PLATFORM}" \
        --tag "${FULL_IMAGE_REF}" \
        --load \
        -f "${PROJECT_ROOT}/Dockerfile" \
        "${PROJECT_ROOT}"
    success "Image built: ${FULL_IMAGE_REF}"
fi

# ---------------------------------------------------------------------------
# Step 2: Verify image exists
# ---------------------------------------------------------------------------
section "[2/6] Verifying image"
if ! docker image inspect "${FULL_IMAGE_REF}" >/dev/null 2>&1; then
    error "Image '${FULL_IMAGE_REF}' not found locally. Run without SKIP_BUILD=1."
    exit 1
fi
success "Image verified"

# ---------------------------------------------------------------------------
# Step 3: Create bundle directory
# ---------------------------------------------------------------------------
section "[3/6] Preparing bundle directory"
mkdir -p "${TARGET_DIR}/config" "${TARGET_DIR}/scripts/lib"
success "Directories created"

# ---------------------------------------------------------------------------
# Step 4: Export image as tar
# ---------------------------------------------------------------------------
TAR_FILE="${TARGET_DIR}/${IMAGE_NAME}-${IMAGE_TAG}.tar"
section "[4/6] Exporting image to ${TAR_FILE}"
info "This may take a few minutes for arm64 images."
docker save -o "${TAR_FILE}" "${FULL_IMAGE_REF}"
TAR_SIZE=$(du -h "${TAR_FILE}" | cut -f1)
success "Image exported (${TAR_SIZE})"

# ---------------------------------------------------------------------------
# Step 5: Copy deployment artifacts
# ---------------------------------------------------------------------------
section "[5/6] Copying deployment artifacts"
ARTIFACTS=(
    "docker-compose.yml"
    "config/base.yaml"
    "config/production.yaml"
    "scripts/deploy.defaults.sh"
    "scripts/pi-install.sh"
    "scripts/pi-configure.sh"
    "scripts/pi-deploy.sh"
    "scripts/rsync-excludes.txt"
    "scripts/lib/health-check.sh"
    "scripts/lib/colors.sh"
    "scripts/pi-load-image.sh"
)

for artifact in "${ARTIFACTS[@]}"; do
    src="${PROJECT_ROOT}/${artifact}"
    dst="${TARGET_DIR}/${artifact}"
    if [[ -f "${src}" ]]; then
        mkdir -p "$(dirname "${dst}")"
        cp "${src}" "${dst}"
        info "  Copied ${artifact}"
    else
        warn "  Missing: ${artifact} (skipped)"
    fi
done

# Write .env
cat > "${TARGET_DIR}/.env" <<ENV
# Generated by bundle-to-drive.sh on $(date '+%Y-%m-%d %H:%M:%S')
TRICORDER_IMAGE=${FULL_IMAGE_REF}
TRICORDER_PORT=${TRICORDER_PORT}
TRICORDER__ENVIRONMENT=production
ENV
info "  Wrote .env"
success "Artifacts copied"

# ---------------------------------------------------------------------------
# Step 6: Generate checksums
# ---------------------------------------------------------------------------
section "[6/6] Generating checksums"
CHECKSUM_FILE="${TARGET_DIR}/SHA256SUMS.txt"

# Use shasum on macOS, sha256sum on Linux
if command -v sha256sum &>/dev/null; then
    HASH_CMD="sha256sum"
elif command -v shasum &>/dev/null; then
    HASH_CMD="shasum -a 256"
else
    warn "No checksum tool found — skipping"
    HASH_CMD=""
fi

if [[ -n "${HASH_CMD}" ]]; then
    cd "${TARGET_DIR}"
    find . -type f ! -name "SHA256SUMS.txt" | sort | while read -r f; do
        ${HASH_CMD} "${f}"
    done > "SHA256SUMS.txt"
    cd - >/dev/null
    success "Checksums written to SHA256SUMS.txt"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
section "Bundle Complete"
info "  Location:   ${TARGET_DIR}"
info "  Image tar:  ${IMAGE_NAME}-${IMAGE_TAG}.tar (${TAR_SIZE})"
info "  Artifacts:  ${#ARTIFACTS[@]} files + .env + checksums"
echo ""
info "To deploy on Pi:"
info "  1. Insert SD/USB into Pi"
info "  2. Mount the drive:  sudo mount /dev/sda1 /mnt/usb"
info "  3. Run:  sudo bash /mnt/usb/scripts/pi-load-image.sh /mnt/usb"
echo ""
